{
 "title": "BIT_ATC",
 "description": "дашборд для АТС",
 "tags": [
  "Linux",
  "ATC"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Всего звонков",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pbxanalytics",
     "rawSql": "SELECT COUNT(*)\r\nFROM pbxanalytics.analytics\r\nWHERE $__timeFilter(calldate)\r\n  AND direction = 'incoming'\r\n  AND modulename = 'call'\r\n  AND (answeredext LIKE '399%' OR answeredext IS NULL OR answeredext = '')\r\n  -- Добавляем наши исключения, чтобы математика сошлась:\r\n  AND dialedext NOT IN ('EXCLUDED_NUMBER_1', 'EXCLUDED_NUMBER_2')\r\n  AND dialedext NOT LIKE '400%'"
    }
   ]
  },
  {
   "title": "Повторные",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pbxanalytics",
     "rawSql": "SELECT COUNT(src) - COUNT(DISTINCT src)\r\nFROM pbxanalytics.analytics \r\nWHERE $__timeFilter(calldate) \r\n  AND direction = 'incoming' \r\n  AND modulename = 'call'"
    }
   ]
  },
  {
   "title": "Ср. длительность",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pbxanalytics",
     "rawSql": "SELECT AVG(billsec) \r\nFROM pbxanalytics.analytics \r\nWHERE $__timeFilter(calldate) \r\n  AND direction = 'incoming' \r\n  AND modulename = 'call' \r\n  AND disposition = 'ANSWERED'"
    }
   ]
  },
  {
   "title": "% пропущенных",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pbxanalytics",
     "rawSql": "SELECT\r\n  (SUM(IF(disposition = 'NOANSWERED', 1, 0)) / NULLIF(COUNT(*), 0)) * 100 AS missed_percent\r\nFROM pbxanalytics.analytics\r\nWHERE $__timeFilter(calldate)\r\n  AND direction = 'incoming'\r\n  AND modulename = 'call'\r\n  AND dialedext NOT IN ('EXCLUDED_NUMBER_1', 'EXCLUDED_NUMBER_2')\r\n  AND dialedext NOT LIKE '400%'"
    }
   ]
  },
  {
   "title": "Отвечено",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pbxanalytics",
     "rawSql": "SELECT COUNT(DISTINCT uniqueid)\r\nFROM pbxanalytics.analytics\r\nWHERE $__timeFilter(calldate)\r\n  AND direction = 'incoming'\r\n  AND modulename = 'call'\r\n  AND disposition = 'ANSWERED'\r\n  AND answeredext LIKE '399%'"
    }
   ]
  },
  {
   "title": "Отвеченные / Пропущенные",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "pbxanalytics",
     "rawSql": "SELECT\r\n  SUM(IF(disposition = 'ANSWERED', 1, 0)) AS 'Отвеченные',\r\n  SUM(IF(disposition = 'NOANSWERED', 1, 0)) AS 'Пропущенные'\r\nFROM pbxanalytics.analytics\r\nWHERE $__timeFilter(calldate)\r\n  AND direction = 'incoming'\r\n  AND modulename = 'call'\r\n  AND dialedext NOT IN ('EXCLUDED_NUMBER_1', 'EXCLUDED_NUMBER_2')\r\n  AND dialedext NOT LIKE '400%'"
    }
   ]
  },
  {
   "title": "SL - ответ за 20с",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pbxanalytics",
     "rawSql": "SELECT \r\n  (SUM(IF(disposition = 'ANSWERED' AND (duration - billsec) <= 20, 1, 0)) / NULLIF(COUNT(*), 0)) * 100\r\nFROM pbxanalytics.analytics \r\nWHERE $__timeFilter(calldate) \r\n  AND direction = 'incoming' \r\n  AND modulename = 'call'"
    }
   ]
  },
  {
   "title": "Макс. ожидание",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pbxanalytics",
     "rawSql": "SELECT MAX(duration - billsec)\r\nFROM pbxanalytics.analytics \r\nWHERE $__timeFilter(calldate) \r\n  AND direction = 'incoming' \r\n  AND modulename = 'call'"
    }
   ]
  },
  {
   "title": "В очереди сейчас",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Aggregate",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "aggregateBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median",
           "first",
           "last"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "1m",
        "sum"
       ],
       "text": "aggregateBy(1m, avg)"
      }
     ],
     "group": { "filter": "ATS" },
     "host": { "filter": "BITATS" },
     "item": { "filter": "/.*Callers/" },
     "itemTag": { "filter": "component: calls" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Активные разговоры",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "ATS" },
     "host": { "filter": "BITATS" },
     "item": { "filter": "Active calls (Irkutsk)" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "false",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Пропущено",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pbxanalytics",
     "rawSql": "SELECT COUNT(*) AS missed_count\r\nFROM pbxanalytics.analytics\r\nWHERE $__timeFilter(calldate)\r\n  AND direction = 'incoming'\r\n  AND modulename = 'call'\r\n  AND disposition = 'NOANSWERED'\r\n  AND dialedext NOT IN ('EXCLUDED_NUMBER_1', 'EXCLUDED_NUMBER_2')\r\n  AND dialedext NOT LIKE '400%'"
    }
   ]
  },
  {
   "title": "Операторы - итог за период",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "pbxanalytics",
     "rawSql": "SELECT\r\n  r.ext AS 'Номер',\r\n  r.name AS 'Оператор',\r\n  IFNULL(a.answered_calls, 0) AS 'Принято',\r\n  ROUND(IFNULL(a.avg_sec, 0) / 60, 2) AS 'Ср.разг,с',\r\n  IFNULL(a.total_calls, 0) AS 'Звонило',\r\n  IFNULL(ROUND((a.answered_calls / a.total_calls) * 100, 1), 0) AS '%поднятия'\r\nFROM pbxanalytics.rt_member_status r\r\nLEFT JOIN (\r\n  SELECT\r\n    answeredext,\r\n    COUNT(*) AS total_calls,\r\n    SUM(CASE WHEN disposition = 'ANSWERED' THEN 1 ELSE 0 END) AS answered_calls,\r\n    AVG(CASE WHEN disposition = 'ANSWERED' THEN billsec ELSE NULL END) AS avg_sec\r\n  FROM pbxanalytics.analytics\r\n  WHERE $__timeFilter(calldate)\r\n    AND direction = 'incoming'\r\n    AND modulename = 'users'\r\n  GROUP BY answeredext\r\n) a ON r.ext = a.answeredext\r\nWHERE r.ext IN (\r\n  '10001',\r\n  '10002',\r\n  '10003'  /* список номеров операторов своей АТС */\r\n)\r\nGROUP BY r.ext, r.name, a.answered_calls, a.avg_sec, a.total_calls\r\nHAVING IFNULL(a.total_calls, 0) > 0\r\nORDER BY IFNULL(a.answered_calls, 0) DESC, r.ext ASC"
    }
   ]
  },
  {
   "title": "Статус транков ",
   "type": "table",
   "gridPos": { "h": 18, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "ATS" },
     "host": { "filter": "BITATS" },
     "item": { "filter": "/Trunk .* status/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}